### ISSUE TITLE
UnicodeDecodeError on non-ASCII characters

### ISSUE THREAD

**Issue by Betree** [promethe42/duralex#1]
I get the following error when trying to run one of the README's example :

```
> ./duralex --url http://www.assemblee-nationale.fr/14/propositions/pion1561.asp
Traceback (most recent call last):
  File "./duralex", line 74, in <module>
    sys.exit(main())
  File "./duralex", line 69, in main
    handle_data(data, args)
  File "./duralex", line 44, in handle_data
    json_data = json.dumps(ast, sort_keys=True, indent=2, ensure_ascii=False).encode('utf-8')
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 210, in encode
    return ''.join(chunks)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 44: ordinal not in range(128)
```

All tests pass successfully :
```
python tests/main.py
...............................................................................................................................
----------------------------------------------------------------------
￼
Ran 127 tests in 0.099s

OK
```

I was able to avoid the crash by setting `ensure_asci` to True in `./bin/duralex` l. 44
```
json.dumps(ast, sort_keys=True, indent=2, ensure_ascii=True)
```

Which produces JSON like that :
```
...
"codeName": "code rural et de la p\u00eache maritime",
...
```

Have you encountered such problems with non ASCII characters previously ?

**Comment by JMLX42** [comment]
Thanks for the bug report.
I've just pushed a potential fix. Please try the latest version.

When I run:

```bash
./duralex --url http://www.assemblee-nationale.fr/14/propositions/pion1561.asp
```

I get:

```json
{
  "children": [
    {
      "children": [
        {
          "children": [
            {
              "children": [
                {
                  "children": [
                    {
                      "children": [
                        {
                          "type": "quote", 
                          "words": "I. -"
                        }
                      ], 
                      "type": "mention"
                    }, 
                    {
                      "children": [
                        {
                          "children": [
                            {
                              "order": 1, 
                              "position": "beginning", 
                              "type": "alinea-reference"
                            }
                          ], 
                          "id": "L. 253-7", 
                          "type": "article-reference"
                        }
                      ], 
                      "codeName": "code rural et de la pêche maritime", 
                      "type": "code-reference"
                    }
                  ], 
                  "editType": "add", 
                  "type": "edit"
                }
              ], 
              "order": 1, 
              "type": "bill-header2"
            }, 
            {
              "children": [
                {
                  "children": [
                    {
                      "children": [
                        {
                          "type": "quote", 
                          "words": "II. - Il est interdit aux personnes publiques mentionnées à l'article L. 1 du code général de la propriété des personnes publiques d'utiliser ou de faire utiliser les produits phytopharmaceutiques visés au premier alinéa de l'article L. 253-1 du présent code, à l'exception de ceux mentionnés au IV du présent article, pour l'entretien des espaces verts, forêts ou promenades accessibles ou ouverts au public et relevant de leur domaine public ou privé. Cette interdiction ne s'applique pas aux traitements et mesures nécessaires à la destruction et à la prévention de la propagation des organismes nuisibles visés à l'article L. 251-3, en application de l'article L. 251-8."
                        }
                      ], 
                      "order": 2, 
                      "type": "header1"
                    }, 
                    {
                      "children": [
                        {
                          "id": "L. 253-7", 
                          "type": "article-reference"
                        }
                      ], 
                      "codeName": "code rural et de la pêche maritime", 
                      "type": "code-reference"
                    }
                  ], 
                  "editType": "add", 
                  "type": "edit"
                }
              ], 
              "order": 2, 
              "type": "bill-header2"
            }
          ], 
          "implicit": true, 
          "order": 1, 
          "type": "bill-header1"
        }
      ], 
      "content": "L'article L. 253-7 du code rural et de la pêche maritime est ainsi modifié :\n1° Au début du premier alinéa est ajoutée la mention : \" I. - \" ;\n2° Il est ajouté un II ainsi rédigé :\n\"II. - Il est interdit aux personnes publiques mentionnées à l'article L. 1 du code général de la propriété des personnes publiques d'utiliser ou de faire utiliser les produits phytopharmaceutiques visés au premier alinéa de l'article L. 253-1 du présent code, à l'exception de ceux mentionnés au IV du présent article, pour l'entretien des espaces verts, forêts ou promenades accessibles ou ouverts au public et relevant de leur domaine public ou privé. Cette interdiction ne s'applique pas aux traitements et mesures nécessaires à la destruction et à la prévention de la propagation des organismes nuisibles visés à l'article L. 251-3, en application de l'article L. 251-8. \"", 
      "isNew": false, 
      "order": 1, 
      "type": "article"
    }, 
    {
      "children": [
        {
          "children": [
            {
              "content": "Le même article L. 253-7 est complété par un III et un IV ainsi rédigés :", 
              "type": "raw-content"
            }
          ], 
          "order": 1, 
          "type": "bill-header1"
        }, 
        {
          "children": [
            {
              "content": "\"III. - La mise sur le marché, la délivrance, l'utilisation et la détention des produits visés au premier alinéa de l'article L. 253-1 pour un usage non professionnel sont interdites, à l'exception de ceux mentionnés au IV du présent article. Cette interdiction ne s'applique pas aux traitements et mesures nécessaires à la destruction et à la prévention de la propagation des organismes nuisibles visés à l'article L. 251-3, en application de l'article L. 251-8.", 
              "type": "raw-content"
            }
          ], 
          "implicit": true, 
          "order": 2, 
          "type": "bill-header1"
        }, 
        {
          "children": [
            {
              "content": "\"IV. - Les II et III ne s'appliquent pas aux produits de bio-contrôle figurant sur une liste établie par l'autorité administrative, aux produits qualifiés à faible risque conformément au règlement (CE) n° 1107/2009 du Parlement européen et du Conseil, du 21 octobre 2009, concernant la mise sur le marché des produits phytopharmaceutiques et abrogeant les directives 79/117/CEE et 91/414/CEE du Conseil, ni aux produits dont l'usage est autorisé dans le cadre de l'agriculture biologique. \"", 
              "type": "raw-content"
            }
          ], 
          "implicit": true, 
          "order": 3, 
          "type": "bill-header1"
        }, 
        {
          "children": [
            {
              "children": [
                {
                  "children": [
                    {
                      "type": "quote", 
                      "words": "et non professionnel"
                    }
                  ], 
                  "type": "words"
                }, 
                {
                  "children": [
                    {
                      "children": [
                        {
                          "children": [
                            {
                              "children": [
                                {
                                  "type": "quote", 
                                  "words": "à usage professionnel"
                                }
                              ], 
                              "position": "after", 
                              "type": "words-reference"
                            }
                          ], 
                          "order": 1, 
                          "type": "alinea-reference"
                        }
                      ], 
                      "id": "L. 253-9", 
                      "type": "article-reference"
                    }
                  ], 
                  "codeName": "code rural et de la pêche maritime", 
                  "type": "code-reference"
                }
              ], 
              "editType": "add", 
              "type": "edit"
            }
          ], 
          "order": 4, 
          "type": "bill-header1"
        }, 
        {
          "children": [
            {
              "children": [
                {
                  "children": [
                    {
                      "type": "quote", 
                      "words": "1° bis Le fait de détenir en vue de la vente, d'offrir en vue de la vente ou de céder sous toute autre forme à titre gratuit ou onéreux, ainsi que le fait de vendre, de distribuer et d'effectuer d'autres formes de cession proprement dites d'un produit interdit dans les conditions posées par le III de l'article L. 253-7 ;"
                    }
                  ], 
                  "isBis": true, 
                  "order": 1, 
                  "type": "header2"
                }, 
                {
                  "children": [
                    {
                      "children": [
                        {
                          "order": 1, 
                          "position": "after", 
                          "type": "header2-reference"
                        }
                      ], 
                      "id": "L. 253-15", 
                      "type": "article-reference"
                    }
                  ], 
                  "codeName": "code rural et de la pêche maritime", 
                  "type": "code-reference"
                }
              ], 
              "editType": "add", 
              "type": "edit"
            }
          ], 
          "order": 5, 
          "type": "bill-header1"
        }
      ], 
      "content": "I. - Le même article L. 253-7 est complété par un III et un IV ainsi rédigés :\n\"III. - La mise sur le marché, la délivrance, l'utilisation et la détention des produits visés au premier alinéa de l'article L. 253-1 pour un usage non professionnel sont interdites, à l'exception de ceux mentionnés au IV du présent article. Cette interdiction ne s'applique pas aux traitements et mesures nécessaires à la destruction et à la prévention de la propagation des organismes nuisibles visés à l'article L. 251-3, en application de l'article L. 251-8.\n\"IV. - Les II et III ne s'appliquent pas aux produits de bio-contrôle figurant sur une liste établie par l'autorité administrative, aux produits qualifiés à faible risque conformément au règlement (CE) n° 1107/2009 du Parlement européen et du Conseil, du 21 octobre 2009, concernant la mise sur le marché des produits phytopharmaceutiques et abrogeant les directives 79/117/CEE et 91/414/CEE du Conseil, ni aux produits dont l'usage est autorisé dans le cadre de l'agriculture biologique. \"\nII. - Au premier alinéa de l'article L. 253-9 du même code, après les mots : \" à usage professionnel \", sont insérés les mots : \" et non professionnel \".\nIII. - Après le 1° de l'article L. 253-15 du même code, il est inséré un 1° bis ainsi rédigé :\n\"1° bis Le fait de détenir en vue de la vente, d'offrir en vue de la vente ou de céder sous toute autre forme à titre gratuit ou onéreux, ainsi que le fait de vendre, de distribuer et d'effectuer d'autres formes de cession proprement dites d'un produit interdit dans les conditions posées par le III de l'article L. 253-7 ; \".", 
      "isNew": false, 
      "order": 2, 
      "type": "article"
    }, 
    {
      "children": [
        {
          "children": [
            {
              "content": "Avant le 31 décembre 2014, le Gouvernement dépose sur le bureau du Parlement un rapport sur le développement de l'utilisation des produits de bio-contrôle et à faible risque mentionnés aux articles 1er et 2, sur les leviers qui y concourent ainsi que sur les recherches menées dans ce domaine. Ce rapport indique les freins juridiques et économiques au développement de ces produits et plus largement à celui de la lutte intégrée telle que définie à l'article 3 de la directive 2009/128/CE du Parlement européen et du Conseil, du 21 octobre 2009, instaurant un cadre d'action communautaire pour parvenir à une utilisation des pesticides compatible avec le développement durable.", 
              "type": "raw-content"
            }
          ], 
          "implicit": true, 
          "order": 1, 
          "type": "bill-header1"
        }
      ], 
      "content": "Avant le 31 décembre 2014, le Gouvernement dépose sur le bureau du Parlement un rapport sur le développement de l'utilisation des produits de bio-contrôle et à faible risque mentionnés aux articles 1er et 2, sur les leviers qui y concourent ainsi que sur les recherches menées dans ce domaine. Ce rapport indique les freins juridiques et économiques au développement de ces produits et plus largement à celui de la lutte intégrée telle que définie à l'article 3 de la directive 2009/128/CE du Parlement européen et du Conseil, du 21 octobre 2009, instaurant un cadre d'action communautaire pour parvenir à une utilisation des pesticides compatible avec le développement durable.", 
      "isNew": false, 
      "order": 3, 
      "type": "article"
    }, 
    {
      "children": [
        {
          "children": [
            {
              "content": "L'article 1er entre en vigueur à compter du 1er janvier 2020.", 
              "type": "raw-content"
            }
          ], 
          "order": 1, 
          "type": "bill-header1"
        }, 
        {
          "children": [
            {
              "content": "L'article 2 entre en vigueur à compter du 1er janvier 2022.", 
              "type": "raw-content"
            }
          ], 
          "order": 2, 
          "type": "bill-header1"
        }
      ], 
      "content": "I. - L'article 1er entre en vigueur à compter du 1er janvier 2020.\nII. - L'article 2 entre en vigueur à compter du 1er janvier 2022.", 
      "isNew": false, 
      "order": 4, 
      "type": "article"
    }
  ], 
  "id": 1561, 
  "legislature": 14, 
  "type": "proposition de loi", 
  "url": "http://www.assemblee-nationale.fr/14/propositions/pion1561.asp"
}
```

**Comment by Betree** [comment]
It works now, thanks :wink:

**Comment by Betree** [comment]
Actually it fixes the problem for HTML pages but causes it when parsing JSON. I was only able working with both by replacing :
```
parent['content'] = text.decode('utf-8') if type(text) == 'unicode' else text
```

By :
```
try:
    parent['content'] = text.decode('utf-8')
except:
    try:
        parent['content'] = text.decode('iso-8859-1')
    except:
        parent['content'] = text
```

**Comment by JMLX42** [comment]
This JSON input format is not documented and should not be used anymore.
I just removed it in bd730f71a7a1174ab14a1ebf17342fd28fc4ed8d.
