### ISSUE TITLE
UnicodeDecodeError on "alinéas" parsing

### ISSUE THREAD

**Issue by mdamien** [promethe42/duralex#4]
To test it, I copy-pasted from the README: `./bin/duralex --url http://www.assemblee-nationale.fr/14/propositions/pion1561.asp`

But I got this error:

```
Traceback (most recent call last):
  File "./bin/duralex", line 104, in <module>
    sys.exit(main())
  File "./bin/duralex", line 99, in main
    handle_data(data, args)
  File "./bin/duralex", line 39, in handle_data
    bill_data = duralex.bill_parser.parse_bill(data, args.url)
  File "---/bin/../duralex/bill_parser.py", line 346, in parse_bill
    cleanup(article)
  File "---/DuraLex/bin/../duralex/bill_parser.py", line 134, in cleanup
    if len(dic['alineas']) == 1 and dic['alineas']['001'].startswith("(Supprimé)"):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8: ordinal not in range(128)
```

I'm looking into it.

**Comment by Reviewver** [comment]
I have the same problem. It's not compatible with Python3.
